### ISSUE TITLE
Feature: Option to specify the gender of the author

### ISSUE THREAD

**Issue by ikelax** [erictapen/typst-invoice#3]
This would be useful since the male form of Kontoinhaberin is Kontoinhaber.

For example, we could add the boolean field `female` to `author`. If it is not set, it is set to `true`.

**Comment by erictapen** [comment]
Would be good to have more flexibility in the future, but I think for now that would be sufficient.

**Comment by erictapen** [comment]
I went with an interface that's a bit more complex, but is hopefully future proof
